import type { ReactNode } from 'react'

function Header() {
  return <header className="site-header"><nav className="site-nav" aria-label="Primary navigation"><a className="site-brand" href="/"><span className="site-brand-mark" aria-hidden="true">✦</span><span>Myztic <strong>Playground</strong></span></a><div className="site-links"><a href="/examples">Examples</a><a href="/security">Security</a><a className="nav-cta" href="/app">Open playground <span aria-hidden="true">→</span></a></div></nav></header>
}

function Footer() {
  return <footer className="site-footer"><div className="section-wrap footer-inner"><div><a className="site-brand" href="/"><span className="site-brand-mark">✦</span><span>Myztic <strong>Playground</strong></span></a><p>A small, fast place to build for the open web.</p></div><nav aria-label="Footer navigation"><a href="/app">Playground</a><a href="/examples">Examples</a><a href="/security">Security</a><a href="https://myztic.dev">Myzticdev ↗</a></nav></div><div className="section-wrap footer-bottom"><span>© 2026 Myzticdev</span><span>Built with care for the open web.</span></div></footer>
}

function PageShell({ children }: { children: ReactNode }) {
  return <div className="site-shell"><Header /><main>{children}</main><Footer /></div>
}

const examples = [
  { kind: 'gradient-example', label: 'CSS • 18 lines', title: 'Animated gradient card', art: <span>soft<br /><em>gradients.</em></span>, description: 'Layer gradients and subtle motion into a polished callout card.' },
  { kind: 'counter-example', label: 'JS • 24 lines', title: 'Interactive counter', art: <><button type="button" tabIndex={-1}>−</button><strong>42</strong><button type="button" tabIndex={-1}>+</button></>, description: 'Wire up a small, accessible counter with vanilla JavaScript.' },
  { kind: 'profile-example', label: 'HTML • 31 lines', title: 'Developer profile card', art: <><span>JD</span><i></i><i></i></>, description: 'Build a responsive profile component using semantic HTML and CSS.' },
  { kind: 'loader-example', label: 'CSS • 16 lines', title: 'Orbit loader', art: <span className="orbit-art"><i></i></span>, description: 'Explore transforms, keyframes, and reduced-motion-friendly animation.' },
  { kind: 'form-example', label: 'HTML • 28 lines', title: 'Sign-up form', art: <><i></i><i></i><button type="button" tabIndex={-1}>Join waitlist</button></>, description: 'Practice labels, inputs, focus states, and concise form validation.' },
  { kind: 'theme-example', label: 'JS • 21 lines', title: 'Theme switcher', art: <><span>☼</span><span>☾</span></>, description: 'Toggle a complete interface theme with custom properties and JavaScript.' },
]

export function ExamplesPage() {
  return <PageShell><section className="page-hero section-wrap"><p className="eyebrow"><span></span> Example projects</p><h1>Start with something small.<br /><em>Make it your own.</em></h1><p>Open a compact frontend idea, inspect how it works, then remix it in Myztic Playground.</p></section><section className="examples-page section-wrap"><div className="example-grid full-grid">{examples.map((example) => <article className={`example-card ${example.kind}`} key={example.title}><div className="example-art">{example.art}</div><div><p><b>{example.label.split(' • ')[0]}</b> • {example.label.split(' • ')[1]}</p><h2>{example.title}</h2><p className="example-description">{example.description}</p><a href="/app">Open in playground <span>→</span></a></div></article>)}</div></section><section className="final-cta section-wrap"><div><p className="eyebrow"><span></span> Begin from zero</p><h2>Prefer a blank canvas?</h2><p>The playground is ready whenever you are.</p></div><a className="primary-cta" href="/app">Open blank playground <span>→</span></a></section></PageShell>
}

export function SecurityPage() {
  return <PageShell><section className="page-hero security-hero section-wrap"><p className="eyebrow"><span></span> Sandbox security</p><h1>Your code stays contained.<br /><em>Here’s how.</em></h1><p>Myztic Playground executes code entirely in your browser, inside a capability-restricted preview designed to keep user code separate from the application.</p></section><section className="security-content section-wrap"><article className="security-summary"><span className="shield-icon">◇</span><div><h2>The short version</h2><p>Your HTML, CSS, and JavaScript are passed one way into a separate preview document. That document runs in an iframe with an opaque origin and only one permission: executing scripts.</p></div></article><div className="security-grid"><article><span>01</span><h2>Opaque-origin iframe</h2><p>The preview uses <code>sandbox="allow-scripts"</code> without <code>allow-same-origin</code>. User code cannot reach the playground page, its DOM, cookies, or local storage.</p></article><article><span>02</span><h2>Network access blocked</h2><p>A strict Content Security Policy sets <code>connect-src 'none'</code> and blocks remote scripts, images, fonts, frames, plugins, and form submissions.</p></article><article><span>03</span><h2>Escape routes removed</h2><p>The sandbox does not grant forms, popups, downloads, modals, or top-level navigation. Preview code cannot open a new window or redirect the playground.</p></article><article><span>04</span><h2>Local-only workspace</h2><p>Your editor contents are stored in your own browser with <code>localStorage</code>. Myztic Playground does not upload your source to a code execution server.</p></article></div><article className="security-limitations"><h2>Important limitations</h2><p>A browser sandbox reduces capabilities; it does not inspect or prove code safe. Resource-heavy scripts and infinite loops can still slow or freeze your own tab. Anyone with access to the same browser profile may also be able to read locally saved code.</p><ul><li>Use an up-to-date browser.</li><li>Do not paste secrets, API keys, or private credentials into browser code.</li><li>Remember that exported projects no longer run inside the playground sandbox.</li></ul></article></section><section className="final-cta section-wrap"><div><p className="eyebrow"><span></span> Explore safely</p><h2>Ready to try an idea?</h2><p>Open the playground and run your frontend code in the isolated preview.</p></div><a className="primary-cta" href="/app">Open playground <span>→</span></a></section></PageShell>
}
