import type { ReactNode } from 'react'
import { exampleProjects, type ExampleSlug } from './examples'

const supportLinks = [
  ['/for-teachers', 'For teachers'],
  ['/learn/html-css-js-playground', 'Learn'],
  ['/alternatives/codepen', 'CodePen alternative'],
  ['/alternatives/jsfiddle', 'JSFiddle alternative'],
] as const

function Header() {
  return <header className="site-header"><nav className="site-nav" aria-label="Primary navigation"><a className="site-brand" href="/"><span className="site-brand-mark" aria-hidden="true">✦</span><span>Myztic <strong>Playground</strong></span></a><div className="site-links"><a href="/examples">Examples</a><a href="/for-teachers">For teachers</a><a href="/security">Security</a><a className="nav-cta" href="/app">Open playground <span aria-hidden="true">→</span></a></div></nav></header>
}

function Footer() {
  return <footer className="site-footer"><div className="section-wrap footer-inner"><div><a className="site-brand" href="/"><span className="site-brand-mark">✦</span><span>Myztic <strong>Playground</strong></span></a><p>A free, local-first place to build for the open web.</p></div><nav aria-label="Footer navigation"><a href="/app">Playground</a><a href="/examples">Examples</a><a href="/about">About</a><a href="/privacy">Privacy</a><a href="/security">Security</a><a href="/changelog">Changelog</a><a href="https://github.com/myzticdev/myztic-playground">GitHub ↗</a></nav></div><div className="section-wrap footer-bottom"><span>© 2026 Myzticdev</span><span>Free. No signup. Built for the open web.</span></div></footer>
}

function PageShell({ children }: { children: ReactNode }) {
  return <div className="site-shell"><Header /><main>{children}</main><Footer /></div>
}

const exampleClassNames: Record<ExampleSlug, string> = {
  'gradient-card': 'gradient-example', counter: 'counter-example', 'profile-card': 'profile-example',
  'orbit-loader': 'loader-example', 'signup-form': 'form-example', 'theme-switcher': 'theme-example',
}

function ExampleArtwork({ slug }: { slug: ExampleSlug }) {
  if (slug === 'gradient-card') return <div className="gradient-mini"><small>CREATIVE CSS</small><strong>soft<br /><em>gradients.</em></strong><i>Explore →</i></div>
  if (slug === 'counter') return <div className="counter-mini"><small>DAILY MOMENTUM</small><strong>42</strong><span><i>−</i><b>Reset</b><i>+</i></span></div>
  if (slug === 'profile-card') return <div className="profile-mini"><span>AM</span><small>FRONTEND ENGINEER</small><strong>Alex Morgan</strong><b>Follow Alex</b></div>
  if (slug === 'orbit-loader') return <div className="loader-mini"><span className="orbit-art"><i></i></span><small>Preparing your workspace</small></div>
  if (slug === 'signup-form') return <div className="form-mini"><small>EARLY ACCESS</small><strong>Build with us.</strong><i></i><i></i><b>Join the waitlist →</b></div>
  return <div className="theme-mini"><small>Myztic Notes</small><span>☼</span><strong>Good interfaces<br />feel inevitable.</strong></div>
}

export function ExamplesPage() {
  return <PageShell><section className="page-hero section-wrap"><p className="eyebrow"><span></span> Example projects</p><h1>Start with something small.<br /><em>Make it your own.</em></h1><p>Open a compact frontend idea, inspect how it works, then remix it in Myztic Playground.</p></section><section className="examples-page section-wrap"><div className="example-grid full-grid">{exampleProjects.map((example) => <article className={`example-card ${exampleClassNames[example.slug]}`} key={example.slug}><div className="example-art"><ExampleArtwork slug={example.slug} /></div><div><p><b>{example.category}</b> • {example.lines} lines</p><h2>{example.title}</h2><p className="example-description">{example.description}</p><a href={`/app?example=${example.slug}`}>Open code in playground <span>→</span></a></div></article>)}</div></section><section className="final-cta section-wrap"><div><p className="eyebrow"><span></span> Begin from zero</p><h2>Prefer a blank canvas?</h2><p>The playground is ready whenever you are.</p></div><a className="primary-cta" href="/app">Open blank playground <span>→</span></a></section></PageShell>
}

type TableRow = { label: string; value: ReactNode }
type Faq = { question: string; answer: ReactNode }

type GuidePageProps = {
  eyebrow: string
  title: ReactNode
  summary: string
  heading: string
  paragraphs: ReactNode[]
  rows?: TableRow[]
  listTitle?: string
  items?: string[]
  faqs: Faq[]
  updated?: string
}

function GuidePage({ eyebrow, title, summary, heading, paragraphs, rows, listTitle, items, faqs, updated = 'July 22, 2026' }: GuidePageProps) {
  return <PageShell>
    <section className="page-hero guide-hero section-wrap"><p className="eyebrow"><span></span> {eyebrow}</p><h1>{title}</h1><p>{summary}</p><p className="updated">Last updated {updated}</p></section>
    <article className="guide-content section-wrap">
      <section className="answer-block"><h2>{heading}</h2>{paragraphs.map((paragraph, index) => <p key={index}>{paragraph}</p>)}</section>
      {rows && <section><h2>At a glance</h2><div className="feature-table" role="table" aria-label="Feature summary">{rows.map((row) => <div className="feature-row" role="row" key={row.label}><strong role="rowheader">{row.label}</strong><span role="cell">{row.value}</span></div>)}</div></section>}
      {items && <section><h2>{listTitle}</h2><ul className="guide-list">{items.map((item) => <li key={item}>{item}</li>)}</ul></section>}
      <section><h2>Frequently asked questions</h2><div className="guide-faq">{faqs.map((faq) => <article key={faq.question}><h3>{faq.question}</h3><p>{faq.answer}</p></article>)}</div></section>
      <aside className="related-links"><h2>Keep exploring</h2><div>{supportLinks.map(([href, label]) => <a href={href} key={href}>{label} <span>→</span></a>)}</div></aside>
    </article>
    <section className="final-cta section-wrap"><div><p className="eyebrow"><span></span> Start immediately</p><h2>Turn an idea into a working page.</h2><p>No setup, account, or payment details required.</p></div><a className="primary-cta" href="/app">Open playground <span>→</span></a></section>
  </PageShell>
}

const coreRows: TableRow[] = [
  { label: 'Price', value: 'Free' }, { label: 'Signup required', value: 'No' },
  { label: 'Languages', value: 'HTML, CSS, and JavaScript' }, { label: 'Live preview', value: 'Yes' },
  { label: 'Project storage', value: 'Locally in your browser' }, { label: 'Export', value: 'HTML, CSS, and JavaScript in a ZIP file' },
]

export function TeachersPage() {
  return <GuidePage eyebrow="For classrooms" title={<>A simple HTML, CSS and JavaScript playground <em>for teachers.</em></>} summary="Run frontend lessons and classroom demos without asking students to install software or create accounts." heading="Teach the open web without setup friction." paragraphs={[<>Myztic Playground gives students three focused editors and a live browser preview. They can practice HTML, CSS, and JavaScript immediately, save work on the same device, and export a ZIP when class is over.</>, <>It works best for short lessons, workshops, demonstrations, and beginner exercises that do not need frameworks or a backend.</>]} rows={coreRows} listTitle="Good classroom uses" items={['Demonstrate how HTML structure, CSS presentation, and JavaScript behavior fit together.', 'Give students a blank workspace without collecting names or email addresses.', 'Download each exercise as ordinary web files for grading or continued local work.', 'Open a prepared example and let students remix it.']} faqs={[{ question: 'Do students need accounts?', answer: 'No. They can open the playground and start coding immediately.' }, { question: 'Can students download their work?', answer: 'Yes. ZIP export downloads index.html, styles.css, and script.js.' }, { question: 'Does it work on school computers?', answer: 'It works in a modern browser and requires no local installation. School network policies may still control access to the site.' }, { question: 'Can it teach frameworks or backend code?', answer: 'No. The playground is intentionally focused on browser-native HTML, CSS, and JavaScript.' }, { question: 'Where is student work stored?', answer: 'The latest project is stored locally in that browser profile, not in a Myztic account.' }]} />
}

export function LearnPage() {
  return <GuidePage eyebrow="Learn by building" title={<>Practice HTML, CSS and JavaScript <em>online.</em></>} summary="Learn frontend basics in a free browser playground with immediate visual feedback, local saving, and downloadable files." heading="The fastest way to learn is to change something and see what happens." paragraphs={[<>Start with HTML to describe the page, CSS to style it, and JavaScript to add behavior. Press Run to see all three work together in the isolated preview.</>, <>Myztic Playground is a scratchpad rather than a course: use it beside a tutorial, open one of the examples, or build a tiny project of your own.</>]} rows={coreRows} listTitle="A useful first exercise" items={['Add a heading, paragraph, and button in the HTML editor.', 'Change colors, spacing, and typography in the CSS editor.', 'Add a click handler in the JavaScript editor.', 'Run the project, then export the result as a ZIP.']} faqs={[{ question: 'Is Myztic Playground suitable for beginners?', answer: 'Yes. Its three-editor layout keeps the relationship between HTML, CSS, and JavaScript visible and direct.' }, { question: 'Do I need to install a code editor?', answer: 'No. Everything runs in your browser.' }, { question: 'Does it include tutorials?', answer: 'It includes remixable examples, but it is a practice workspace rather than a complete course.' }, { question: 'Will my code still be there later?', answer: 'The latest project is restored when you return with the same browser profile, unless local site data has been cleared.' }, { question: 'Can I continue in VS Code?', answer: 'Yes. Export the project as a ZIP, extract it, and open the files in your preferred editor.' }]} />
}

export function ExportPage() {
  return <GuidePage eyebrow="Portable projects" title={<>Export HTML, CSS and JavaScript <em>as a ZIP.</em></>} summary="Build a frontend experiment online, then download ordinary web files you can open, share, or continue editing locally." heading="Your playground project is not locked in." paragraphs={[<>Choose Download ZIP to export the current project as <code>index.html</code>, <code>styles.css</code>, and <code>script.js</code>. The HTML file is automatically connected to the stylesheet and script.</>, <>After extraction, open index.html in a browser or continue working in any local code editor. The exported project contains your code only—no Myztic analytics or playground runtime.</>]} rows={[...coreRows, { label: 'Files included', value: 'index.html, styles.css, script.js' }]} listTitle="How to export" items={['Write or edit your project in the three code panels.', 'Press Run and confirm the preview looks right.', 'Choose Download ZIP in the top toolbar.', 'Extract the archive and open index.html.']} faqs={[{ question: 'What files are in the ZIP?', answer: 'The archive contains index.html, styles.css, and script.js.' }, { question: 'Are the files connected already?', answer: 'Yes. The exported HTML links to styles.css and loads script.js with defer.' }, { question: 'Can I host the exported project?', answer: 'Yes. It is a static frontend project suitable for any static web host, subject to the requirements of your own code.' }, { question: 'Does export include analytics?', answer: 'No. The downloaded project contains only the project files generated from your editors.' }, { question: 'Can I re-import a ZIP?', answer: 'Not currently. ZIP export is a one-way download feature.' }]} />
}

export function CodePenPage() {
  return <GuidePage eyebrow="CodePen alternative" title={<>Myztic Playground vs <em>CodePen.</em></>} summary="Choose a lightweight, no-signup workspace for quick frontend tests—or CodePen when public sharing and community features matter." heading="Use Myztic Playground when speed, privacy, and portable files matter most." paragraphs={[<>Myztic Playground is a focused CodePen alternative for quick HTML, CSS, and JavaScript experiments. It requires no account, saves the latest project locally, and exports a ready-to-use ZIP.</>, <>CodePen is the stronger choice for public pens, profiles, social discovery, embeds, collaboration, preprocessors, and portfolio work. The right tool depends on whether you need a private scratchpad or a publishing community.</>]} rows={[{ label: 'No-signup editing', value: 'Myztic Playground' }, { label: 'Local browser save', value: 'Myztic Playground' }, { label: 'Three-file ZIP export', value: 'Myztic Playground' }, { label: 'Community and discovery', value: 'CodePen' }, { label: 'Public profiles and portfolios', value: 'CodePen' }, { label: 'Preprocessors and collaboration', value: 'CodePen' }]} faqs={[{ question: 'Is Myztic Playground a replacement for every CodePen feature?', answer: 'No. It intentionally focuses on quick browser-native experiments rather than social publishing or collaboration.' }, { question: 'Which tool is simpler for an anonymous test?', answer: 'Myztic Playground is designed for immediate no-signup testing with local save.' }, { question: 'Which is better for a public portfolio?', answer: 'CodePen is better suited to public profiles, discovery, and portfolio presentation.' }, { question: 'Can Myztic export a project?', answer: 'Yes. It downloads standard HTML, CSS, and JavaScript files in a ZIP.' }, { question: 'Does Myztic support preprocessors?', answer: 'No. It stays focused on browser-native HTML, CSS, and JavaScript.' }]} />
}

export function JsFiddlePage() {
  return <GuidePage eyebrow="JSFiddle alternative" title={<>Myztic Playground vs <em>JSFiddle.</em></>} summary="Use a simple no-signup HTML/CSS/JS workspace with local save and ZIP export, or choose JSFiddle for library-heavy testing." heading="Myztic Playground keeps beginner and quick-test workflows deliberately small." paragraphs={[<>For straightforward frontend experiments, Myztic Playground provides three editors, an isolated live preview, local autosave, and ZIP export without account setup.</>, <>JSFiddle is a better fit when you need its broad framework and external-library options, embedding workflow, or other advanced fiddle settings.</>]} rows={[{ label: 'No-signup editing', value: 'Myztic Playground' }, { label: 'Local browser save', value: 'Myztic Playground' }, { label: 'Three-file ZIP export', value: 'Myztic Playground' }, { label: 'Framework/library selection', value: 'JSFiddle' }, { label: 'Embedding and fiddle settings', value: 'JSFiddle' }, { label: 'Best beginner workflow', value: 'Myztic Playground' }]} faqs={[{ question: 'Is Myztic Playground a JSFiddle alternative for beginners?', answer: 'Yes. It offers a smaller browser-native workflow with no signup and a direct ZIP export.' }, { question: 'Can I add external libraries in Myztic?', answer: 'No. Network access is blocked inside the preview, so inline browser-native code is the intended use.' }, { question: 'Which tool is better for React or framework testing?', answer: 'JSFiddle is generally the better fit when external frameworks and libraries are required.' }, { question: 'Where does Myztic save code?', answer: 'It saves the latest project in local browser storage on the current device and browser profile.' }, { question: 'Can I download my Myztic project?', answer: 'Yes. Export produces a ZIP with wired-together HTML, CSS, and JavaScript files.' }]} />
}

export function PrivacyPage() {
  return <GuidePage eyebrow="Privacy" title={<>Your code stays <em>local.</em></>} summary="Myztic Playground stores your latest project in your browser and does not upload source code to a code-execution service." heading="A local-first frontend scratchpad." paragraphs={[<>Editor contents are saved with your browser’s local storage so the latest project can be restored on the same browser profile. Myztic Playground has no user accounts or project database.</>, <>Optional site analytics may be enabled by a deployment owner, but user project source and exported files are not included in analytics events. Respect browser privacy controls and never paste secrets into frontend code.</>]} rows={[{ label: 'Account data', value: 'None—accounts are not offered' }, { label: 'Project source', value: 'Stored in local browser storage' }, { label: 'Server-side code execution', value: 'None' }, { label: 'ZIP contents', value: 'Your HTML, CSS, and JavaScript only' }, { label: 'Clearing saved work', value: 'Clear the editors or the site’s local browser data' }]} faqs={[{ question: 'Is my code uploaded to Myztic?', answer: 'No. Project code is not sent to a Myztic code-execution server.' }, { question: 'Can another device see my saved project?', answer: 'No. Local storage does not synchronize projects between devices or browser profiles.' }, { question: 'What happens if I clear browser data?', answer: 'Locally saved playground work may be permanently removed, so export important projects first.' }, { question: 'Should I paste API keys into the editor?', answer: 'No. Secrets do not belong in browser code, locally saved content, or exported frontend projects.' }, { question: 'Does the downloaded ZIP contain tracking code?', answer: 'No. ZIP exports contain only the generated project files.' }]} />
}

export function AboutPage() {
  return <GuidePage eyebrow="About Myztic Playground" title={<>A small tool for the <em>open web.</em></>} summary="Myztic Playground is maintained by Myzticdev as a free, focused place to learn, teach, prototype, and test frontend code." heading="Why Myztic Playground exists." paragraphs={[<>Frontend ideas should be easy to test. Myztic Playground removes accounts, installations, build steps, and project setup from small HTML, CSS, and JavaScript experiments.</>, <>The project is intentionally lightweight and open source. Its clearest strengths are live preview, local browser saving, an isolated sandbox, and portable ZIP export—not social feeds or cloud hosting.</>]} rows={coreRows} faqs={[{ question: 'Who maintains Myztic Playground?', answer: <><a href="https://myztic.dev">Myzticdev</a> maintains the project.</> }, { question: 'Is the source code available?', answer: <><a href="https://github.com/myzticdev/myztic-playground">Yes, the project is available on GitHub.</a></> }, { question: 'What is the tool best for?', answer: 'Learning, classroom demos, quick prototypes, UI experiments, and small browser-native tests.' }, { question: 'Is it a backend compiler?', answer: 'No. It is a frontend browser playground for HTML, CSS, and JavaScript.' }, { question: 'How can I follow updates?', answer: <><a href="/changelog">Read the changelog</a> for notable product changes.</> }]} />
}

export function ChangelogPage() {
  return <GuidePage eyebrow="Changelog" title={<>What’s new in <em>Myztic Playground.</em></>} summary="A concise record of meaningful improvements to the editor, examples, security, and supporting content." heading="July 2026 — clearer, more discoverable, and easier to learn from." paragraphs={[<>Added dedicated pages for teachers, learners, ZIP export, privacy, and honest comparisons with CodePen and JSFiddle. Expanded machine-readable metadata, FAQs, and internal navigation.</>, <>Recent releases also added six remixable examples, an isolated live preview, local autosave, ZIP export, responsive marketing pages, and optional privacy-aware analytics.</>]} items={['Free HTML, CSS, and JavaScript editor with explicit Run and Stop controls.', 'Opaque-origin preview sandbox with network access disabled.', 'Local project restoration and three-file ZIP export.', 'Example gallery with projects that open directly in the editor.', 'Crawlable homepage copy, structured data, sitemap, and AI-readable site summary.']} listTitle="Current capabilities" faqs={[{ question: 'How often is the changelog updated?', answer: 'It is updated when a release adds or materially changes a user-facing capability.' }, { question: 'Where can I report a problem?', answer: <><a href="https://github.com/myzticdev/myztic-playground/issues">Open an issue on GitHub.</a></> }, { question: 'Is there a public repository?', answer: <><a href="https://github.com/myzticdev/myztic-playground">Yes. The source is available on GitHub.</a></> }, { question: 'Do updates remove locally saved code?', answer: 'Normal releases do not intentionally clear local browser storage, but important work should always be exported.' }, { question: 'Is Myztic Playground still free?', answer: 'Yes. It remains free and requires no account.' }]} />
}

export function SecurityPage() {
  return <PageShell><section className="page-hero security-hero section-wrap"><p className="eyebrow"><span></span> Sandbox security</p><h1>Your code stays contained.<br /><em>Here’s how.</em></h1><p>Myztic Playground executes code entirely in your browser, inside a capability-restricted preview designed to keep user code separate from the application.</p></section><section className="security-content section-wrap"><article className="security-summary"><span className="shield-icon">◇</span><div><h2>The short version</h2><p>Your HTML, CSS, and JavaScript are passed one way into a separate preview document. That document runs in an iframe with an opaque origin and only one permission: executing scripts.</p></div></article><div className="security-grid"><article><span>01</span><h2>Opaque-origin iframe</h2><p>The preview uses <code>sandbox="allow-scripts"</code> without <code>allow-same-origin</code>. User code cannot reach the playground page, its DOM, cookies, or local storage.</p></article><article><span>02</span><h2>Network access blocked</h2><p>A strict Content Security Policy sets <code>connect-src 'none'</code> and blocks remote scripts, images, fonts, frames, plugins, and form submissions.</p></article><article><span>03</span><h2>Escape routes removed</h2><p>The sandbox does not grant forms, popups, downloads, modals, or top-level navigation. Preview code cannot open a new window or redirect the playground.</p></article><article><span>04</span><h2>Local-only workspace</h2><p>Your editor contents are stored in your own browser with <code>localStorage</code>. Myztic Playground does not upload your source to a code execution server.</p></article></div><article className="security-limitations"><h2>Important limitations</h2><p>A browser sandbox reduces capabilities; it does not inspect or prove code safe. Resource-heavy scripts and infinite loops can still slow or freeze your own tab. Anyone with access to the same browser profile may also be able to read locally saved code.</p><ul><li>Use an up-to-date browser.</li><li>Do not paste secrets, API keys, or private credentials into browser code.</li><li>Remember that exported projects no longer run inside the playground sandbox.</li></ul></article></section><section className="final-cta section-wrap"><div><p className="eyebrow"><span></span> Explore safely</p><h2>Ready to try an idea?</h2><p>Open the playground and run your frontend code in the isolated preview.</p></div><a className="primary-cta" href="/app">Open playground <span>→</span></a></section></PageShell>
}
